name: Build-Test-Push
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test
jobs:
  build-and-push:
     runs-on: ubuntu-latest 
     steps:
            - uses: actions/checkout@v2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login do docker hub
              env:
                DOCKER_USER: ${{ secrets.DOCKER_USER }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: build-push-image                  
              id: docker_build 
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                platforms: linux/amd64,linux/arm64
                push: true
                tags: abhay900/dev:latest
  Build-Test-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build rootless image
        run: ./build-rootless.sh $(echo $GITHUB_REPOSITORY |cut -d '/' -f1)
      - name: Build standard image
        run: ./build.sh $(echo $GITHUB_REPOSITORY |cut -d '/' -f1)
      - name: Run tests
        run: cd tests; ./run_tests.sh
      - name: Tag Docker images
        run: |
          docker tag puppet-dev-tools:latest-rootless ${{ secrets.DOCKERHUB_PUSH_USERNAME }}/puppet-dev-tools:$(date +"%F")-$(git rev-parse --short HEAD)-rootless
          docker tag puppet-dev-tools:latest ${{ secrets.DOCKERHUB_PUSH_USERNAME }}/puppet-dev-tools:$(date +"%F")-$(git rev-parse --short HEAD)
      - name: List Docker images
        run: docker images --filter "reference=puppet-dev-tools*" --filter "reference=*/puppet-dev-tools*"
      - name: Show Docker image labels
        run: |
          docker inspect --format='{{json .Config.Labels}}' ${{ secrets.DOCKERHUB_PUSH_USERNAME }}/puppet-dev-tools:$(date +"%F")-$(git rev-parse --short HEAD)
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKERHUB_PUSH_USERNAME }}/puppet-dev-tools:$(date +"%F")-$(git rev-parse --short HEAD)-rootless
          docker push ${{ secrets.DOCKERHUB_PUSH_USERNAME }}/puppet-dev-tools:$(date +"%F")-$(git rev-parse --short HEAD)
